services:
  frontend:
    build:
      context: .
      dockerfile: .dockerfiles/prod/frontend.Dockerfile
    container_name: corcel_frontend
    ports:
      - "80:80"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: .dockerfiles/prod/backend.Dockerfile
    container_name: corcel_backend
    env_file:
      - ./api/.env
    environment:
      - LANGUAGETOOL_URL=http://languagetool:8010
    volumes:
      - backend_temp_uploads:/app/api/temp_uploads
      - backend_images:/app/api/images
      - backend_logs:/app/logs
    depends_on:
      - db
      - languagetool
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: corcel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - ./api/.env
    restart: unless-stopped

  languagetool:
    image: erikvl87/languagetool:latest
    container_name: corcel_languagetool
    environment:
      Java_Xms: 512m
      Java_Xmx: 1g
    networks:
      - app_network
    restart: unless-stopped

  backups:
    image: prodrigestivill/postgres-backup-local
    container_name: corcel_backups
    depends_on:
      - db
    volumes:
      - ./backups/dumps:/backups
    networks:
      - app_network
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_HOST=db
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  backend_temp_uploads:
  backend_images:
  backend_logs:
